### PR TITLE
fix syntax errors in README

### PR DESCRIPTION
**Pull request by michaelficarra**
arrows have the precedence of assignment expressions

### CODE REVIEW

**Comment by michaelficarra** [comment]
Ping @jaydson.

**Comment by jaydson** [comment]
Both ways are valid @michaelficarra.
Have you had any trouble running the example?

**Comment by michaelficarra** [comment]
@jaydson That's not true. Check the grammar. Async arrows (and all arrows) have AssignmentExpression precedence. Or just try it in the node REPL. V8 gets this right.

**Comment by jaydson** [comment]
You're totally right @michaelficarra !
Thanks for the fix and sorry for the absurd delay for accepting this PR.

**Pull request merged**
